### ISSUE TITLE
Feat/Spell Rarity Colours - Dark Theme UI

### ISSUE THREAD

**Issue by MindWeb125** [xdy/xdy-pf2e-workbench#642]
Just a very small one, but the Feat/Spell Rarity Option doesn't play super nice with dark theme UIs.

Would it be possible to add an additional option that makes the Common rarity a brighter colour?

![Foundry_Virtual_Tabletop_dgNlbamUmx](https://user-images.githubusercontent.com/105242276/216334505-af4b98ec-b6f0-4fe2-9c7e-0e7d60b25670.png)

**Comment by xdy** [comment]
The colours are the same same colours the system uses for rarities so as to make it easier to remember what the colors mean.
The dark mode is from Dorako's module right? (https://github.com/Dorako/pf2e-dorako-ui/) If so, make an issue on their github.
(I thought Dorako had done something about the colors on dark mode already, but I could misremember.)

**Comment by MindWeb125** [comment]
> The colours are the same same colours the system uses for rarities so as to make it easier to remember what the colors mean. The dark mode is from Dorako's module right? (https://github.com/Dorako/pf2e-dorako-ui/) If so, make an issue on their github. (I thought Dorako had done something about the colors on dark mode already, but I could misremember.)

Aaaah, sorry, I'll put something up on Dorako's! Sorry for wasting your time.

**Comment by Dorako** [comment]
Just dropping by to say that the version of Dorako UI I released yesterday stopped injecting the stylesheet on load, but instead added it to the module.json.
This caused xdy-pf2e-workbench styles to apply later than pf2e-dorako-ui styles of the same specificity, thus undoing a bunch of styling all over the place.
I reverted this in the newest release, causing the Dorako UI-adjusted rules to take precedence despite having the same css specificity.

**Comment by Dorako** [comment]
For context, this is what Dorako UI does:
```css
.xdy-pf2e-workbench-rarity-common {
  color: var(--rarity-common);
  border-color: var(--rarity-common);
}

.xdy-pf2e-workbench-rarity-uncommon {
  color: var(--rarity-uncommon);
  border-color: var(--rarity-uncommon);
}

.xdy-pf2e-workbench-rarity-rare {
  color: var(--rarity-rare);
  border-color: var(--rarity-rare);
}

.xdy-pf2e-workbench-rarity-unique {
  color: var(--rarity-unique);
  border-color: var(--rarity-unique);
}
```

And I'm then adjusting the color referenced by the CSS-variable depending on whether the context is dark or light.
I'd contribute this to workbench, but sadly the system isn't exposing the rarity colors as css variables, just SASS ones, which are calculated at design-time. (meaning I need to first do a system PR and then a workbench PR)
